In [2]:
import torch
from torch import nn
from torch.nn import functional as F

net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))

X = torch.rand(size=(2, 20))
net(X)

tensor([[ 1.1009e-01,  9.2717e-02, -2.7462e-02, -3.1071e-01, -1.0717e-01,
         -2.3865e-01,  6.0450e-02,  3.8751e-02, -1.4864e-05,  2.0225e-01],
        [ 4.5657e-02,  4.1685e-02,  6.0646e-02, -2.3540e-01, -2.1767e-01,
         -1.8146e-01,  9.4981e-02,  1.6363e-01, -4.2947e-02,  2.2788e-01]],
       grad_fn=<AddmmBackward0>)

In [3]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)

    def forward(self, X):
        return self.out(F.relu(self.hidden(X))) 

net = MLP()
net(X)

tensor([[ 0.2093, -0.0867, -0.0293,  0.0773,  0.0816, -0.0660, -0.1818, -0.1548,
         -0.0919,  0.0189],
        [ 0.1275, -0.0321, -0.0359,  0.2135,  0.1290,  0.0024, -0.2289, -0.0568,
         -0.0428, -0.0532]], grad_fn=<AddmmBackward0>)

In [19]:
class MySequential(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for i, block in enumerate(args):
            self.add_module(''.join(['zhx', str(i), 'zhx']), block)
            # self._modules[i] = block
            # print(self._modules)
    
    def forward(self, X):
        # print(self._modules)
        # print(self._modules.keys())
        # print(self._modules.values())
        # print(self._modules.items())
        for block in self._modules.values():
            X = block(X)
        return X

net = MySequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))
print(net)
print(net.state_dict())
net(X)

MySequential(
  (zhx0zhx): Linear(in_features=20, out_features=256, bias=True)
  (zhx1zhx): ReLU()
  (zhx2zhx): Linear(in_features=256, out_features=10, bias=True)
)
OrderedDict([('zhx0zhx.weight', tensor([[-0.1972, -0.0679,  0.2108,  ...,  0.0641,  0.0685,  0.0042],
        [-0.0051, -0.1091,  0.1752,  ...,  0.1591,  0.0496,  0.0805],
        [ 0.2116,  0.0739, -0.0511,  ..., -0.1658,  0.0035,  0.0312],
        ...,
        [ 0.2128, -0.1436, -0.0048,  ...,  0.1962,  0.0796, -0.1639],
        [-0.1459,  0.1434,  0.0642,  ..., -0.0586, -0.0203, -0.0533],
        [ 0.0181,  0.1846,  0.0326,  ..., -0.1461,  0.0095, -0.1848]])), ('zhx0zhx.bias', tensor([-0.1488,  0.1981, -0.0441, -0.1765, -0.1587, -0.0113,  0.0501,  0.2136,
        -0.0981,  0.0414,  0.0195, -0.0412, -0.0128, -0.0329,  0.0310, -0.0805,
        -0.0257,  0.0020, -0.0891,  0.1313,  0.1872, -0.1374,  0.1126, -0.1961,
        -0.1184, -0.0515,  0.1772, -0.0042,  0.0453,  0.1147, -0.2032, -0.0024,
         0.0186,  0.2095, -0.

tensor([[-0.1185, -0.1768,  0.1484,  0.1791, -0.0622,  0.1661, -0.0674,  0.0157,
         -0.0850, -0.0673],
        [-0.0541, -0.0632,  0.1574,  0.1301,  0.0108,  0.1929, -0.1207,  0.0157,
         -0.0308, -0.1161]], grad_fn=<AddmmBackward0>)