In [2]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

tensor([[-0.0667],
        [ 0.0346]], grad_fn=<AddmmBackward0>)

In [5]:
print(net[0].state_dict())
print(net[2].state_dict())
print(net.state_dict())

OrderedDict([('weight', tensor([[ 3.5792e-01,  4.3745e-01, -1.8116e-01,  4.9952e-01],
        [ 3.9634e-01,  6.0746e-02, -8.3045e-02,  6.7411e-02],
        [ 1.3808e-01, -2.1440e-01,  1.7564e-01,  4.6653e-01],
        [-1.6345e-01, -4.9643e-01, -4.1949e-02, -2.6233e-01],
        [ 3.1801e-01,  4.6023e-01, -4.4265e-01,  2.5398e-01],
        [ 4.7668e-02, -4.2801e-01,  2.0656e-02,  3.7724e-01],
        [ 1.3583e-01, -1.3582e-01,  3.2929e-01, -3.4457e-01],
        [ 2.8479e-04, -3.3709e-01,  1.7144e-01, -3.0330e-02]])), ('bias', tensor([-0.0397, -0.2870,  0.3128,  0.2042,  0.1565, -0.0314,  0.3341, -0.1710]))])
OrderedDict([('weight', tensor([[-0.2673, -0.3136,  0.2206, -0.2633, -0.3076,  0.1721,  0.2945,  0.2225]])), ('bias', tensor([-0.1347]))])
OrderedDict([('0.weight', tensor([[ 3.5792e-01,  4.3745e-01, -1.8116e-01,  4.9952e-01],
        [ 3.9634e-01,  6.0746e-02, -8.3045e-02,  6.7411e-02],
        [ 1.3808e-01, -2.1440e-01,  1.7564e-01,  4.6653e-01],
        [-1.6345e-01, -4.9643e-01

In [9]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)
print(net[2].bias.grad)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([-0.1347], requires_grad=True)
tensor([-0.1347])
None


In [21]:
for name, param in net.named_parameters():
    print(name, param)
    print(type(param))
for name, param in net.state_dict().items():
    print(name, param)
    print(type(param))

net.state_dict()['2.bias'].data

0.weight Parameter containing:
tensor([[ 3.5792e-01,  4.3745e-01, -1.8116e-01,  4.9952e-01],
        [ 3.9634e-01,  6.0746e-02, -8.3045e-02,  6.7411e-02],
        [ 1.3808e-01, -2.1440e-01,  1.7564e-01,  4.6653e-01],
        [-1.6345e-01, -4.9643e-01, -4.1949e-02, -2.6233e-01],
        [ 3.1801e-01,  4.6023e-01, -4.4265e-01,  2.5398e-01],
        [ 4.7668e-02, -4.2801e-01,  2.0656e-02,  3.7724e-01],
        [ 1.3583e-01, -1.3582e-01,  3.2929e-01, -3.4457e-01],
        [ 2.8479e-04, -3.3709e-01,  1.7144e-01, -3.0330e-02]],
       requires_grad=True)
<class 'torch.nn.parameter.Parameter'>
0.bias Parameter containing:
tensor([-0.0397, -0.2870,  0.3128,  0.2042,  0.1565, -0.0314,  0.3341, -0.1710],
       requires_grad=True)
<class 'torch.nn.parameter.Parameter'>
2.weight Parameter containing:
tensor([[-0.2673, -0.3136,  0.2206, -0.2633, -0.3076,  0.1721,  0.2945,  0.2225]],
       requires_grad=True)
<class 'torch.nn.parameter.Parameter'>
2.bias Parameter containing:
tensor([-0.1347], req

tensor([-0.1347])